language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - rvm use $RVM --install --binary --fuzzy
  - gem update --system
  - gem --version
notifications:
  recipients:
    - bernardstanislas@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - RVM=2.0.0 LANG="en_US.UTF-8"
os:
  - linux
