language: cpp
compiler:
  - gcc
before_install:
  - sh build.sh
notifications:
  recipients:
    - bernardstanislas@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - RVM=2.0.0 LANG="en_US.UTF-8"
os:
  - linux
